// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

/**@author Tyler Fleig
 */
package org.usfirst.frc78.AirStrike2014.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;
import edu.wpi.first.wpilibj.command.WaitCommand;

/**
 *
 */
public class AutoTwoBall extends CommandGroup {
    
    private final static double DRIVE_SPEED = 0.75;
    private final static double DRIVE_TIME = 1.0;
    
    public  AutoTwoBall() {
        addSequential(new DriveWithJoysticks(),0.1);
        addSequential(new ShootAndReloadBallWPause());
        addSequential(new IntakeOneBallFull(),7.0);
        addSequential(new WaitCommand(0.5));
        addSequential(new ShootAndReloadBallWPause());
        addSequential(new DriveStraight(DRIVE_SPEED, DRIVE_TIME));
        
        
    }
}
