// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc78.AirStrike2014.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;
import edu.wpi.first.wpilibj.command.WaitCommand;

/**
 *
 */
public class AutoOneBallHot extends CommandGroup {
    
    private static final double DRIVE_SPEED = 0.75;
    private static final double DRIVE_TIME = 1.0;
    
    public  AutoOneBallHot() {
        addSequential(new LEDOn());
        addSequential(new WaitForHot());
        addParallel(new ShootAndReloadBallWPause());
        addParallel(new LEDOff());
        addSequential(new WaitCommand(0.75));
        addParallel(new IntakeFastStore());
        addParallel(new DriveStraight(DRIVE_SPEED, DRIVE_TIME));
    }
}

