// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

/**@author Tyler Fleig
 */

package org.usfirst.frc78.AirStrike2014.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;
import edu.wpi.first.wpilibj.command.WaitCommand;

/**
 *
 */
public class IntakeOneBallHalf extends CommandGroup {
    
    public  IntakeOneBallHalf() {
        
        setInterruptible(false);
        addSequential(new IntakeStartWheelsIn());
        addSequential(new IntakeFastIntake());
        addSequential(new WaitForBall());
        addSequential(new WaitCommand(0.2));
        addSequential(new IntakeStopWheels());
    }
}
