// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

/**@author Tyler Fleig
 */

package org.usfirst.frc78.AirStrike2014.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;
import edu.wpi.first.wpilibj.command.WaitCommand;
import org.usfirst.frc78.AirStrike2014.Robot;

/**
 *
 */
public class ShootAndReloadBallWPause extends CommandGroup {
    
    public  ShootAndReloadBallWPause() {
        setInterruptible(false);
        addSequential(new StartChooChoo());
        addSequential(new WaitCommand(1.0));
        //addSequential(new WaitForMagEncoder());
        addSequential(new WaitForChooChooSensors());
       // addSequential(new WaitCommand(0.05));
        addSequential(new StopChooChoo());



        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
    }
}
