// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc78.AirStrike2014.commands;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import org.usfirst.frc78.AirStrike2014.Robot;
/**
 *
 */
public class  WaitForChooChooSensors extends Command {
    final double RELOAD_VAL = 2.450; //CHANGE VALID MAX TOO
    final double RELOAD_POS_TOLERANCE = 0.1;
    
    final double VALID_MAX = 3.5;//CHANGE WITH VALID MAX
    double encoderMax = 0;
    double encoderCurrentVal= 0;
    public WaitForChooChooSensors() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.shooter);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        setTimeout(5.0);
    }
    // Called just before this Command runs the first time
    protected void initialize() {
        encoderMax = 0;
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        encoderCurrentVal = Robot.shooter.getChooChooEncoder();
        if(encoderCurrentVal > encoderMax)
            encoderMax = encoderCurrentVal;
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return Robot.shooter.getChooChooLimit()||
                Robot.shooter.getChooChooSecondLimit()||
                isTimedOut();
    }
    // Called once after isFinished returns true
    protected void end() {
        if(encoderMax < VALID_MAX){
            Robot.shooter.encoderIsValid = false;
        }
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
